export type PensionDividend = {
  date: string;
  amount: string;
};

export type StatementTransferContract = {
  id?: string;
  transferContractAmount: string;
  transferContractCompanyId: string;
  transferContractCompany: string;
  transferContractDate: string;
  transferContractFirstPaymentDate: string;
  transferContractIsOppv: boolean;
  transferContractNumber: string;
  transferContractRegNumber: string;
};

export type PensionApp = {
  id: string;
  processInstanceId: string;
  masterProcessId: string | null;
  contractDate: string;
  contractStartDate: string;
  contractEndDate: string;
  contractId: string | null;
  contractNumber: string | null;
  frequencyPayments: string;
  periodPayments: string;
  guaranteedPeriod: number;
  insuranceProgramType: string;
  amount: string;
  isSpokesman: boolean;
  compulsoryContract: string | null;
  compulsoryContractNumber: string | null;
  compulsoryContractDate: string | null;
  compulsoryContractAmount: string;
  compulsoryProfContract: string | null;
  compulsoryProfContractNumber: string | null;
  compulsoryProfContractDate: string | null;
  compulsoryProfContractAmount: string;
  compulsoryProfMonthCount: string;
  voluntaryContract: string | null;
  voluntaryContractCompany: string | null;
  voluntaryContractNumber: string | null;
  voluntaryContractDate: string | null;
  voluntaryContractAmount: string;
  bankId: number;
  bankName: string;
  bankBik: string;
  bankBin: string;
  account: string;
  payDay: number;
  dateOfBegin: string;
  dateOfEnd: string | null;
  paymentSettlement: number;
  payment: number;
  pensionAnnuityMinSum: string;
  factorCurrentValue: number;
  totalAnnuityFactor: number;
  annuityFactor: number;
  premiumRate: number | null;
  indexRate: number;
  effectRate: number;
  policyId: string | null;
  totalAnnuityFactorWithoutExpenses: number;
  factorCurrentValueGp: number;
  factorCurrentValueGpYear: number;
  factorCurrentValueYear: number;
  parentPolicyId: string | null;
  refundAmount: string;
  refundAmountMax: string;
  parentContractNumber: string | null;
  parentContractAmount: string;
  parentContractMainAmount: string;
  parentContractNextPay: string | null;
  parentContractNextPayDate: string | null;
  alfa: number;
  gamma: number;
  isOppvDefineAuto: boolean | null;
  isContractClosed: boolean | null;
  closeContractCompanyCode: string | null;
  closeContractCompanyName: string | null;
  ownFundsRaisAmount: string;
  transferContractIsOppv: boolean | null;
  transferContractFirstPaymentDate: string | null;
  transferContractAmount: string;
  transferContractDate: string | null;
  transferContractNumber: string | null;
  transferContractRegNumber: string | null;
  transferContract: string | null;
  transferContractCompany: string | null;
  transferContractMonthCount: number | null;
  isOnlineEnpfAgreement: boolean;
  isEnpfSum: boolean;
  isCalculated: boolean;
  transferContracts: StatementTransferContract[] | null;
  dividendId: string;
  dividends: PensionDividend[] | null;
  isOwnAmountFromDividend: boolean | null;
};
