import type { SokStatus } from './types';

export type Program = {
  programType: number;
  programName: string;
  insisProgramType: string;
  mainCoversTeritory: string;
  transplantationTeritory: string;
  isSameTerriotory: boolean;
  isFranchisable: boolean;
  currency: number;
  flightAndAccommodationPersonCount: number;
  code: string;
  nameKz: string;
  nameRu: string;
  id: string;
};

export type PolicyAppDto = {
  id: string;
  processInstanceId: string;
  policyId: string | null;
  parentContractId: string;
  policyNumber: string | null;
  contractDate: string;
  contractEndDate: string;
  amount: string | null;
  premium: number | null;
  effectiveAnnualpercentage: string;
  indexRateId: string;
  paymentPeriodId: string;
  calcDirect: number;
  activeTab: string;
  mainCoverPremium: number | null;
  currency: CurrencyNames | '';
  isSpokesman: boolean;
  coverPeriod: string;
  payPeriod: string;
  annualIncome: number | null;
  lifeMultiply: string;
  lifeAdditive: string;
  adbMultiply: string;
  adbAdditive: string;
  disabilityMultiply: string;
  disabilityAdditive: string;
  riskGroup: number;
  premiumInCurrency: string | null;
  amountInCurrency: string | null;
  hasEnhancedGift: boolean;
  currencyExchangeRate: string;
  futureAutoProlongation: boolean;
  accureStartEducationCapital: boolean;
  showAccureStartEducationalCapitalSwitch: boolean;
  accureStartEducationalCapitalStatus: SokStatus;
  indexRateCode: string;
  indexRateName: string;
  paymentPeriodName: string;
  documentSignTypeId: string | null;
  documentSignTypeCode: string;
  documentSignTypeName: string;
  isDocumentsSigned: boolean | null;
  paymentTypeId: string | null;
  paymentTypeName: string;
  isPayed: boolean | null;
  underwritingType: number;
  tariffId: string | null;
  tariffName: string;
  riskGroup2: number | null;
  lifeMultiplyClient: string | null;
  lifeAdditiveClient: string | null;
  annuityTypeId: string;
  annuityTypeName: string;
  annuityPaymentPeriodId: string;
  annuityPaymentPeriodName: string;
  guaranteedPaymentPeriod: number;
  paymentPeriod: number;
  annuityMonthPay: string;
  calcDate: string | null;
  guaranteedPaymentBeginDate: string | null;
  guaranteedPaymentEndDate: string | null;
  annuityPaymentAmount: number | null;
  countPay: number | null;
  guaranteedPeriod: number | null;
  factorCurrentValueGP: number | null;
  alfa: number | null;
  gamma: number | null;
  mrpPayment: number | null;
  statePremium5: string;
  totalAmount5: string;
  statePremium7: string;
  totalAmount7: string;
  fixInsSum: number;
  insrCount: number;
  mainPremium: string;
  mainPremiumWithCommission: string;
  mainInsSum: string;
  fgotId: string | null;
  fgotValue: number;
  parentContractNumber: string | null;
  parentContractInsrBegin: string | null;
  addPrem: number | null;
  addPremInCurrency: number | null;
  isFranchised: boolean;
  program: Program;
};
